name: Release

on:
  push:
    branches:
        - main
        - develop
        - release/**

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build
              if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
              run: npm run build
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
